# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  system.userActivationScripts.linktosharedfolder.text = ''
    # Documentos personales
    if [[ ! -h "$HOME/Documents/Documentos personales" ]]; then
      ln -s "/hdd/home/gambled/Nextcloud/Documentos personales" "$HOME/Documents/Documentos personales"
    fi

    # Modular
    if [[ ! -h "$HOME/Documents/Modular" ]]; then
      ln -s "/hdd/home/gambled/Nextcloud/Modular" "$HOME/Documents/Modular"
    fi

    # Wallpapers
    if [[ ! -h "$HOME/Pictures/Wallpapers" ]]; then
      ln -s "/hdd/home/gambled/Nextcloud/Wallpapers" "$HOME/Pictures/Wallpapers"
    fi

    # Codes
    if [[ ! -h "$HOME/Codes" ]]; then
      ln -s "/hdd/home/gambled/Codes/" "$HOME/Codes"
    fi

    # Documents
    if [[ ! -h "$HOME/Documents" ]]; then
      ln -s "/hdd/home/gambled/Documents/" "$HOME/Documents"
    fi

    # Downloads
    if [[ ! -h "$HOME/Downloads" ]]; then
      ln -s "/hdd/home/gambled/Downloads/" "$HOME/Downloads"
    fi

    # Music
    if [[ ! -h "$HOME/Music" ]]; then
      ln -s "/hdd/home/gambled/Music/" "$HOME/Music"
    fi

    # Nextcloud
    if [[ ! -h "$HOME/Nextcloud" ]]; then
      ln -s "/hdd/home/gambled/Nextcloud/" "$HOME/Nextcloud"
    fi

    # Pictures
    if [[ ! -h "$HOME/Pictures" ]]; then
      ln -s "/hdd/home/gambled/Pictures/" "$HOME/Pictures"
    fi

    # Videos
    if [[ ! -h "$HOME/Videos" ]]; then
      ln -s "/hdd/home/gambled/Videos/" "$HOME/Videos"
    fi
  '';
}
