# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  system.userActivationScripts.linktosharedfolder.text = ''
    # Wallpapers
    if [[ ! -h "$HOME/Pictures/Wallpapers" ]]; then
      ln -s "/home/gambled/Nextcloud/Wallpapers/" "$HOME/Pictures/Wallpapers"
    fi
  '';
}
