# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  system.userActivationScripts.linktosharedfolder.text = ''
    if [[ ! -h "$HOME/hass_backups" ]]; then
      ln -s "/var/lib/hass/backups" "$HOME/hass_backups"
    fi
  '';
}
